### ISSUE TITLE
Fix responsiveness 

### ISSUE THREAD

**Issue by ySnoopyDogy** [MenheraBot/MenheraSite#24]
# Hacktoberfest

Today Menhera's Site responsiveness its pretty bad, the route `donate` is the worst of all. 
If someone can make a better responsive system, i would be glad

**Comment by Daniel-Vinicius** [comment]
Hello @ySnoopyDogy I'm Daniel and I'm participating in Hacktoberfest, this is my first contribution, sorry for my english, I'm going to make the donate page responsive.

**Comment by ySnoopyDogy** [comment]
Hey daniel, thank you for you help, good luck with it. Beijinhos

**Comment by Daniel-Vinicius** [comment]
@ySnoopyDogy this is right?

Wasn't it supposed to count 1 in progress?
Because I created a PR that still needs to be approved.
Or is it like that?

![image](https://user-images.githubusercontent.com/66279500/135689456-2eda5c9a-61a2-4a8c-bb5b-7eb7cfdc1182.png)
