### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by ySnoopyDogy** [MenheraBot/MenheraSite#25]
# Hacktoberfest

The SEO of Menhera's Site its garbage. I cannot find the website by searching like `Menhera Bot`, which should be the first survey of users trying to access it.

Searching by `Menhera Bot` returns first Top.GG sites (no problem), but when it shows Menhera's Site, the title its 'Hey, my name is Menhera Bot' (I guess its because the first h1 is that, i dont know), but i want to display like "Menhera Site" and the description show like a description of what MenheraBot is.

I dont know anything of SEO and how to improve it, so i really need your help

**Comment by Gabriel-Paulucci** [comment]
I know how to do this and I can solve this problem for you

**Comment by ySnoopyDogy** [comment]
Okyyy, wait one day to count to hacktoberfest

**Comment by Gabriel-Paulucci** [comment]
Apparently looking at your code, the reason Google is coming up with another title is because your `h1` is more flashy than your `title`

h1: `Olá, meu nome é Menhera Bot`
title: `Menhera's Site`

Maybe if you remove `Site` it will pass q index with `Manhera's`
But doing this would be more on the basis of the test because as he is not using the title of your site, it is more annoying to modify this

**Comment by ySnoopyDogy** [comment]
We can try

**Comment by Gabriel-Paulucci** [comment]
Would you like me to standardize the social media titles too?

Twitter: `Menhera's Site`
Og: `Menhera'Site`

**Comment by ySnoopyDogy** [comment]
Menhera'Site is actually a Typing error, you can put `Menhera's Site` in all of it

**Comment by Gabriel-Paulucci** [comment]
Doing some research tests, I noticed if you search

`menhera bot`

![image](https://user-images.githubusercontent.com/43076727/135502888-bea158bd-146b-4359-847b-739b21f40180.png)

`menhera's site`

![image](https://user-images.githubusercontent.com/43076727/135502995-b879a4e4-224a-41b8-a80b-01eaa9e14acc.png)

**Comment by ySnoopyDogy** [comment]
yeah, i want to change the `menhera bot` search to display `Menhera's Site` too, maybe we need to change the website name, like to MenheraBot, i dont know what is better

**Comment by Gabriel-Paulucci** [comment]
Probably as the search keywords are relatively different, he starts using his h1 which is more similar

**Comment by ySnoopyDogy** [comment]
Using VPN i saw that the search return the portuguese description. Is that a way to localize website descriptions?
![image](https://user-images.githubusercontent.com/59155752/135503465-9887114a-41d0-4af5-ab17-e299bbf672e2.png)

**Comment by Gabriel-Paulucci** [comment]
It probably returns this description because the default value is in Portuguese right?

**Comment by ySnoopyDogy** [comment]
Yeah yeah, i dont know if there is a way to localize it, but if exists, i would like to do it so

**Comment by Gabriel-Paulucci** [comment]
I believe that using the description meta tag there is no way to change it because if I'm not mistaken to do this it would have to be something more like this 

![image](https://user-images.githubusercontent.com/43076727/135504174-1d885044-9bf7-4e69-b6ac-14cd7584df0a.png)

**Comment by ySnoopyDogy** [comment]
oooh i see, no problem so. I will keep it in portuguese as 90% of the users are brazilians

**Comment by Gabriel-Paulucci** [comment]
> 
> 
> yeah, i want to change the `menhera bot` search to display `Menhera's Site` too, maybe we need to change the website name, like to MenheraBot, i dont know what is better

Acredito que para vc poderia colocar `Menhera's Bot`

**Comment by ySnoopyDogy** [comment]
Menhera's Bot significa "Bot da Menhera", se fosse assim ai teria que por só Menhera Bot

**Comment by Gabriel-Paulucci** [comment]
Makes sense, then use `Menhera Bot`

**Comment by ySnoopyDogy** [comment]
Ok, let's use it
