### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Daniel-Vinicius** [MenheraBot/MenheraSite#30]
Guys, I would like to contribute to the project again, I saw that there are no tests, what do you think about starting to write tests?

There is this guide on how to integrate the next to the testing library

https://nextjs.org/docs/testing#jest-and-react-testing-library

If you like I can start configuring and doing the first tests.

**Comment by ySnoopyDogy** [comment]
I have never create tests to front end,. I think it is a good idea. Go ahead, and thanks again for the help
