### ISSUE TITLE
404 Not Working

### ISSUE THREAD

**Issue by ySnoopyDogy** [MenheraBot/MenheraSite#9]
The 404 works when the page is after /:lang/ BUT, with the rewrite, the /pt/status become /status, and if the user just put like /stttt it returns an error.

/pt/stsras - 404 working
/stsras - Error 

I dont know how to fix. I tried redirects with next, and got no success :(

**Comment by Gabriel-Paulucci** [comment]
Apparently this error has been resolved 
This is not happening anymore

**Comment by ySnoopyDogy** [comment]
On localhost it works, but in production it doesnt
https://menherabot.xyz/asd

**Comment by Gabriel-Paulucci** [comment]
It's weird because, the only thing I can think of is i18n not being able to recognize what lang is, but it's even weirder that it's only happening in production

**Comment by ySnoopyDogy** [comment]
Fixed
